force-app/main/default/objects/ApprovalRequest__c/ApprovalRequest__c.object-meta.xml
<CustomObject>
    <label>ApprovalRequest</label>
    <nameField>
        <label>ApprovalRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApprovalRequests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalRequest__c/fields/ApprovalStep__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStep__c</fullName>
    <label>ApprovalStep</label>
    <referenceTo>ApprovalStep__c</referenceTo>
    <relationshipLabel>ApprovalRequests</relationshipLabel>
    <relationshipName>ApprovalRequests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ApprovalRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalRequest__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Decided</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApprovalStep__c/ApprovalStep__c.object-meta.xml
<CustomObject>
    <label>ApprovalStep</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ApprovalStep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ApprovalSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ApprovalRequestHandler.cls
/**
 * Created by StefanieHerbst on 6/2/2021.
 */

public with sharing class ApprovalRequestHandler extends TriggerHandlerExtension{

    List<ApprovalStep__c> approvalStepUpdateList = new List<ApprovalStep__c>();

    public ApprovalRequestHandler(){
        super();
    }

    public override void bulkAfter() {
        System.debug('approvalRequestHandlerInsert1');
        if (Trigger.isInsert) {
            System.debug('approvalRequestHandlerInsert');
            initiiereApprovalProcesses(Trigger.new);
        } else if (Trigger.isUpdate){
        //schreibeEntscheidungAufApprovalRequest();
        //schreibeApprovalEntscheidungAufApprovalStep();
    }
    }

  /*  private void initiiereApprovalProcesses(){



        if(oldRequest.Decision__c == 'Not Decided' && newRequest.Decision__c != 'Not Decided'){
            schreibeApprovalEntscheidungAufApprovalStep(newRequest);
        }
    }*/

    public override void andFinally(){
        if(!approvalStepUpdateList.isEmpty()){
            update approvalStepUpdateList;
        }
    }

    public void initiiereApprovalProcesses(List<ApprovalRequest__c> newList){
        System.debug('approverprocess : ' + newList);
        for (ApprovalRequest__c appReq : newList) {
            approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setObjectId(appReq.id);
            req.setNextApproverIds(new Id[]{
                    appReq.Approver__c
            });
            System.debug('req: ' + req);
            Approval.ProcessResult result = Approval.process(req);
            System.debug('result: ' + result);        }
    }

    public void schreibeApprovalEntscheidungAufApprovalStep(ApprovalRequest__c request){
        ApprovalStep__c parentStep = new ApprovalStep__c();

        parentStep.Id = request.ApprovalStep__c;
        parentStep.Decision__c = request.Decision__c;

        approvalStepUpdateList.add(parentStep);
    }
}