force-app/main/default/objects/ApprovalStep__c/ApprovalStep__c.object-meta.xml
<CustomObject>
    <label>ApprovalStep</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ApprovalStep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ApprovalSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalStep__c/fields/ApproverRole__c.field-meta.xml
<CustomField>
    <fullName>ApproverRole__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver Role</label>
    <referenceTo>ApproverRole__c</referenceTo>
    <relationshipLabel>ApprovalSteps</relationshipLabel>
    <relationshipName>ApprovalSteps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalStep__c/fields/priorizationApprovalProcess__c.field-meta.xml
<CustomField>
    <fullName>priorizationApprovalProcess__c</fullName>
    <label>priorizationApprovalProcess</label>
    <referenceTo>priorizationApprovalProcess__c</referenceTo>
    <relationshipLabel>ApprovalSteps</relationshipLabel>
    <relationshipName>ApprovalSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApproverRole__c/ApproverRole__c.object-meta.xml
<CustomObject>
    <label>Approver Role</label>
    <nameField>
        <label>Approver Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Approver Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MatrixToFindCommitee__mdt/MatrixToFindCommitee__mdt.object-meta.xml
<CustomObject>
    <label>MatrixToFindCommitee</label>
    <pluralLabel>MatrixToFindCommitees</pluralLabel>
</CustomObject>

force-app/main/default/objects/MatrixToFindCommitee__mdt/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatrixToFindCommitee__mdt/fields/ApproverRole__c.field-meta.xml
<CustomField>
    <fullName>ApproverRole__c</fullName>
    <label>ApproverRole</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatrixToFindCommitee__mdt/fields/Lieferstandort__c.field-meta.xml
<CustomField>
    <fullName>Lieferstandort__c</fullName>
    <label>Lieferstandort</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatrixToFindCommitee__mdt/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MatrixToFindCommitee__mdt/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product_Family</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/priorizationApprovalProcess__c/priorizationApprovalProcess__c.object-meta.xml
<CustomObject>
    <label>priorizationApprovalProcess</label>
    <nameField>
        <label>priorizationApprovalProcess__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>priorizationApprovalProcesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/userAssignment__c/userAssignment__c.object-meta.xml
<CustomObject>
    <label>userAssignment</label>
    <nameField>
        <label>userAssignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>userAssignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/userAssignment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/userAssignment__c/fields/ApproverRole__c.field-meta.xml
<CustomField>
    <fullName>ApproverRole__c</fullName>
    <label>ApproverRole</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/userAssignment__c/fields/Lieferstandort__c.field-meta.xml
<CustomField>
    <fullName>Lieferstandort__c</fullName>
    <label>Lieferstandort</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/userAssignment__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>Plant</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/userAssignment__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/userAssignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>userAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApprovalStepHandler.cls
/**
 * Created by StefanieHerbst on 6/2/2021.
 */

public with sharing class ApprovalStepHandler extends TriggerHandlerExtension{

    public ApprovalStepHandler(){
        super();
    }

    private void beforeInsert(List<ApprovalStep__c> listNew) {
        Map<id, id> userProcessIdMap = nehmeUserMitRichtigemUserAssignment(listNew);
        erstelleApprovalRequest(userProcessIdMap);
    }

    private Map<id, id> nehmeUserMitRichtigemUserAssignment(List<ApprovalStep__c> listNew) {

        Map<id, id> userProcessIdMap = new Map<id, id>();
        List<priorizationApprovalProcess__c> prioApprProcess = [
                select id, Opportunity__r.Account__c, Opportunity__r.Plant__c,
                        Opportunity__r.Lieferstandort__c, Opportunity__r.Product_Family__c
                from priorizationApprovalProcess__c
        ]; //where id list von approvalste.priorizationApprovalProzess in ..... fehlt noch

        for (priorizationApprovalProcess__c process : prioApprProcess) {

            List<MatrixToFindCommitee__mdt> neededUserRolesHelper = [
                    Select ApproverRole__c
                    from MatrixToFindCommitee__mdt
                    where Account__c = :process.opportunity__r.Account__c and
                    Lieferstandort__c = :process.opportunity__r.Lieferstandort__c and
                    Plant__c = :process.opportunity__r.plant__c and Product_Family__c = :process.opportunity__r.Product_Family__c
            ];

            for (MatrixToFindCommitee__mdt helper : neededUserRolesHelper) {
                userProcessIdMap.put(helper.ApproverRole__c, process.id);
            }
        }

        return userProcessIdMap;
    }

    private void erstelleApprovalRequest(Map<id, id> userProcessIdMap) {
        List<userAssignment__c> userToBeAssignedList = [Select Id, User__c from userAssignment__c where ApproverRole__c in :userProcessIdMap.keySet()];

        for (userAssignment__c userToBeAssigned : userToBeAssignedList) {
            approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
            req.setObjectId(userProcessIdMap.get(userToBeAssigned.user__C));
            req.setNextApproverIds(new Id[]{
                    userToBeAssigned.User__c
            });
        }
    }


    private void deaktiviereAlleZugehoerigenApprovalRequests() {

    }

    private void pruefeObAlleApprovalStepsGefuelltSind() {

    }

    private void updateStatusVonPriorizationApprovalProcess() {

    }
}