force-app/main/default/objects/ApprovalStep__c/ApprovalStep__c.object-meta.xml
<CustomObject>
    <label>ApprovalStep</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>ApprovalStep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ApprovalSteps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalStep__c/fields/priorizationApprovalProcess__c.field-meta.xml
<CustomField>
    <fullName>priorizationApprovalProcess__c</fullName>
    <label>priorizationApprovalProcess</label>
    <referenceTo>priorizationApprovalProcess__c</referenceTo>
    <relationshipLabel>ApprovalSteps</relationshipLabel>
    <relationshipName>ApprovalSteps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/priorizationApprovalProcess__c/priorizationApprovalProcess__c.object-meta.xml
<CustomObject>
    <label>priorizationApprovalProcess</label>
    <nameField>
        <label>priorizationApprovalProcess__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>priorizationApprovalProcesses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/priorizationApprovlProcessTriggerHandler.cls
/**
 * Created by StefanieHerbst on 6/2/2021.
 */

public with sharing class priorizationApprovlProcessTriggerHandler {

    private void beforeInsert(List<priorizationApprovalProcess__c> listNew) {
        erstelleApprovalStepsmitHilfeVonMatrix(listNew);
    }

    private void beforeUpdate(List<priorizationApprovalProcess__c> listNew) {
        updateStatusAufOpportunity(listNew);
        setztePriorizationApprovalProcessInaktiv(listNew);
    }

    private void erstelleApprovalStepsmitHilfeVonMatrix(List<priorizationApprovalProcess__c> listNew) {
        List<ApprovalStep__c> appStepList = new List <ApprovalStep__c>();

        for(priorizationApprovalProcess__c process : listNew){
            ApprovalStep__c appStep = new ApprovalStep__c();
            appStep.priorizationApprovalProcess__c = process.id;
            appStepList.add(appStep);
        }

        if (!appStepList.isEmpty() && appStepList != null) {
            insert appStepList;
        }
    }

    private void updateStatusAufOpportunity(List<priorizationApprovalProcess__c> listNew) {

    }

    private void setztePriorizationApprovalProcessInaktiv(List<priorizationApprovalProcess__c> listNew) {

    }
}